// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: shared/proto/fvnet/fv_network.proto

package fvnet

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope_Type int32

const (
	Envelope_PING                  Envelope_Type = 0
	Envelope_PONG                  Envelope_Type = 1
	Envelope_MAP_CHUNK             Envelope_Type = 2
	Envelope_CREATURE_UPDATE       Envelope_Type = 3
	Envelope_CLIENT_REQUEST_REGION Envelope_Type = 4
	Envelope_SERVER_STATUS         Envelope_Type = 5
	Envelope_WORLD_STATUS          Envelope_Type = 6
	Envelope_VEGETATION_UPDATE     Envelope_Type = 7
	Envelope_TILETYPE_LIST         Envelope_Type = 8
	Envelope_MATERIAL_LIST         Envelope_Type = 9
)

// Enum value maps for Envelope_Type.
var (
	Envelope_Type_name = map[int32]string{
		0: "PING",
		1: "PONG",
		2: "MAP_CHUNK",
		3: "CREATURE_UPDATE",
		4: "CLIENT_REQUEST_REGION",
		5: "SERVER_STATUS",
		6: "WORLD_STATUS",
		7: "VEGETATION_UPDATE",
		8: "TILETYPE_LIST",
		9: "MATERIAL_LIST",
	}
	Envelope_Type_value = map[string]int32{
		"PING":                  0,
		"PONG":                  1,
		"MAP_CHUNK":             2,
		"CREATURE_UPDATE":       3,
		"CLIENT_REQUEST_REGION": 4,
		"SERVER_STATUS":         5,
		"WORLD_STATUS":          6,
		"VEGETATION_UPDATE":     7,
		"TILETYPE_LIST":         8,
		"MATERIAL_LIST":         9,
	}
)

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}

func (x Envelope_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_fvnet_fv_network_proto_enumTypes[0].Descriptor()
}

func (Envelope_Type) Type() protoreflect.EnumType {
	return &file_shared_proto_fvnet_fv_network_proto_enumTypes[0]
}

func (x Envelope_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_Type.Descriptor instead.
func (Envelope_Type) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{0, 0}
}

// Envelope para qualquer mensagem via WebSocket
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Envelope_Type          `protobuf:"varint,1,opt,name=type,proto3,enum=fvnet.Envelope_Type" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_Type {
	if x != nil {
		return x.Type
	}
	return Envelope_PING
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MapChunkMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	ChunkZ        int32                  `protobuf:"varint,3,opt,name=chunk_z,json=chunkZ,proto3" json:"chunk_z,omitempty"`
	VoxelData     []byte                 `protobuf:"bytes,4,opt,name=voxel_data,json=voxelData,proto3" json:"voxel_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChunkMessage) Reset() {
	*x = MapChunkMessage{}
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChunkMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChunkMessage) ProtoMessage() {}

func (x *MapChunkMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChunkMessage.ProtoReflect.Descriptor instead.
func (*MapChunkMessage) Descriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{1}
}

func (x *MapChunkMessage) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *MapChunkMessage) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *MapChunkMessage) GetChunkZ() int32 {
	if x != nil {
		return x.ChunkZ
	}
	return 0
}

func (x *MapChunkMessage) GetVoxelData() []byte {
	if x != nil {
		return x.VoxelData
	}
	return nil
}

type ClientRequestRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CenterX       int32                  `protobuf:"varint,1,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	CenterY       int32                  `protobuf:"varint,2,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	CenterZ       int32                  `protobuf:"varint,3,opt,name=center_z,json=centerZ,proto3" json:"center_z,omitempty"`
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequestRegion) Reset() {
	*x = ClientRequestRegion{}
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestRegion) ProtoMessage() {}

func (x *ClientRequestRegion) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestRegion.ProtoReflect.Descriptor instead.
func (*ClientRequestRegion) Descriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{2}
}

func (x *ClientRequestRegion) GetCenterX() int32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *ClientRequestRegion) GetCenterY() int32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *ClientRequestRegion) GetCenterZ() int32 {
	if x != nil {
		return x.CenterZ
	}
	return 0
}

func (x *ClientRequestRegion) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DfConnected   bool                   `protobuf:"varint,2,opt,name=df_connected,json=dfConnected,proto3" json:"df_connected,omitempty"`
	TrackedUnits  int32                  `protobuf:"varint,3,opt,name=tracked_units,json=trackedUnits,proto3" json:"tracked_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{3}
}

func (x *ServerStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStatus) GetDfConnected() bool {
	if x != nil {
		return x.DfConnected
	}
	return false
}

func (x *ServerStatus) GetTrackedUnits() int32 {
	if x != nil {
		return x.TrackedUnits
	}
	return 0
}

type WorldStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorldName  string                 `protobuf:"bytes,1,opt,name=world_name,json=worldName,proto3" json:"world_name,omitempty"`
	Year       int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Day        int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Month      string                 `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"`
	Season     string                 `protobuf:"bytes,5,opt,name=season,proto3" json:"season,omitempty"`
	Population int32                  `protobuf:"varint,6,opt,name=population,proto3" json:"population,omitempty"`
	// Sincronização de posição (onde o DF está olhando)
	ViewX         int32 `protobuf:"varint,7,opt,name=view_x,json=viewX,proto3" json:"view_x,omitempty"`
	ViewY         int32 `protobuf:"varint,8,opt,name=view_y,json=viewY,proto3" json:"view_y,omitempty"`
	ViewZ         int32 `protobuf:"varint,9,opt,name=view_z,json=viewZ,proto3" json:"view_z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldStatus) Reset() {
	*x = WorldStatus{}
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldStatus) ProtoMessage() {}

func (x *WorldStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_fvnet_fv_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldStatus.ProtoReflect.Descriptor instead.
func (*WorldStatus) Descriptor() ([]byte, []int) {
	return file_shared_proto_fvnet_fv_network_proto_rawDescGZIP(), []int{4}
}

func (x *WorldStatus) GetWorldName() string {
	if x != nil {
		return x.WorldName
	}
	return ""
}

func (x *WorldStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *WorldStatus) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *WorldStatus) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *WorldStatus) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *WorldStatus) GetPopulation() int32 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *WorldStatus) GetViewX() int32 {
	if x != nil {
		return x.ViewX
	}
	return 0
}

func (x *WorldStatus) GetViewY() int32 {
	if x != nil {
		return x.ViewY
	}
	return 0
}

func (x *WorldStatus) GetViewZ() int32 {
	if x != nil {
		return x.ViewZ
	}
	return 0
}

var File_shared_proto_fvnet_fv_network_proto protoreflect.FileDescriptor

const file_shared_proto_fvnet_fv_network_proto_rawDesc = "" +
	"\n" +
	"#shared/proto/fvnet/fv_network.proto\x12\x05fvnet\"\xce\x01\n" +
	"\bEnvelope\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.fvnet.Envelope.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"~\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\b\n" +
	"\x04PONG\x10\x01\x12\r\n" +
	"\tMAP_CHUNK\x10\x02\x12\x13\n" +
	"\x0fCREATURE_UPDATE\x10\x03\x12\x19\n" +
	"\x15CLIENT_REQUEST_REGION\x10\x04\x12\x11\n" +
	"\rSERVER_STATUS\x10\x05\x12\x10\n" +
	"\fWORLD_STATUS\x10\x06\"{\n" +
	"\x0fMapChunkMessage\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\x17\n" +
	"\achunk_z\x18\x03 \x01(\x05R\x06chunkZ\x12\x1d\n" +
	"\n" +
	"voxel_data\x18\x04 \x01(\fR\tvoxelData\"~\n" +
	"\x13ClientRequestRegion\x12\x19\n" +
	"\bcenter_x\x18\x01 \x01(\x05R\acenterX\x12\x19\n" +
	"\bcenter_y\x18\x02 \x01(\x05R\acenterY\x12\x19\n" +
	"\bcenter_z\x18\x03 \x01(\x05R\acenterZ\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\"p\n" +
	"\fServerStatus\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fdf_connected\x18\x02 \x01(\bR\vdfConnected\x12#\n" +
	"\rtracked_units\x18\x03 \x01(\x05R\ftrackedUnits\"\xe5\x01\n" +
	"\vWorldStatus\x12\x1d\n" +
	"\n" +
	"world_name\x18\x01 \x01(\tR\tworldName\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\x12\x14\n" +
	"\x05month\x18\x04 \x01(\tR\x05month\x12\x16\n" +
	"\x06season\x18\x05 \x01(\tR\x06season\x12\x1e\n" +
	"\n" +
	"population\x18\x06 \x01(\x05R\n" +
	"population\x12\x15\n" +
	"\x06view_x\x18\a \x01(\x05R\x05viewX\x12\x15\n" +
	"\x06view_y\x18\b \x01(\x05R\x05viewY\x12\x15\n" +
	"\x06view_z\x18\t \x01(\x05R\x05viewZB#Z!FortressVision/shared/proto/fvnetb\x06proto3"

var (
	file_shared_proto_fvnet_fv_network_proto_rawDescOnce sync.Once
	file_shared_proto_fvnet_fv_network_proto_rawDescData []byte
)

func file_shared_proto_fvnet_fv_network_proto_rawDescGZIP() []byte {
	file_shared_proto_fvnet_fv_network_proto_rawDescOnce.Do(func() {
		file_shared_proto_fvnet_fv_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_fvnet_fv_network_proto_rawDesc), len(file_shared_proto_fvnet_fv_network_proto_rawDesc)))
	})
	return file_shared_proto_fvnet_fv_network_proto_rawDescData
}

var file_shared_proto_fvnet_fv_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_fvnet_fv_network_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_fvnet_fv_network_proto_goTypes = []any{
	(Envelope_Type)(0),          // 0: fvnet.Envelope.Type
	(*Envelope)(nil),            // 1: fvnet.Envelope
	(*MapChunkMessage)(nil),     // 2: fvnet.MapChunkMessage
	(*ClientRequestRegion)(nil), // 3: fvnet.ClientRequestRegion
	(*ServerStatus)(nil),        // 4: fvnet.ServerStatus
	(*WorldStatus)(nil),         // 5: fvnet.WorldStatus
}
var file_shared_proto_fvnet_fv_network_proto_depIdxs = []int32{
	0, // 0: fvnet.Envelope.type:type_name -> fvnet.Envelope.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_fvnet_fv_network_proto_init() }
func file_shared_proto_fvnet_fv_network_proto_init() {
	if File_shared_proto_fvnet_fv_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_fvnet_fv_network_proto_rawDesc), len(file_shared_proto_fvnet_fv_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_fvnet_fv_network_proto_goTypes,
		DependencyIndexes: file_shared_proto_fvnet_fv_network_proto_depIdxs,
		EnumInfos:         file_shared_proto_fvnet_fv_network_proto_enumTypes,
		MessageInfos:      file_shared_proto_fvnet_fv_network_proto_msgTypes,
	}.Build()
	File_shared_proto_fvnet_fv_network_proto = out.File
	file_shared_proto_fvnet_fv_network_proto_goTypes = nil
	file_shared_proto_fvnet_fv_network_proto_depIdxs = nil
}
